renderCategoryFilter=function(){const el=document.getElementById('categoryFilter'),cur=el.value||'全部';el.innerHTML=['全部',...v3Cats()].map(c=>`<option ${c===cur?'selected':''}>${escapeHtml(c)}</option>`).join('')};
renderSupplierTabs=function(){document.getElementById('supplierTabs').innerHTML=v3Suppliers().map(s=>`<button class="${s===activeSupplier?'active':''}" data-supplier="${escapeHtml(s)}">${escapeHtml(s)}</button>`).join('')};
renderStock=function(){
  const q=document.getElementById('searchInput').value.trim().toLowerCase(),cat=document.getElementById('categoryFilter').value||'全部',rows=v3Skus().filter(x=>(cat==='全部'||x.category===cat)&&(!q||`${x.name} ${x.spec} ${x.supplier}`.toLowerCase().includes(q)));
  document.getElementById('stockList').innerHTML=rows.length?rows.map(x=>{const use=v3WeeklyUse(x);return `<article class="sku-card"><div class="sku-top"><div class="sku-main"><div class="sku-icon">${v3Icon(x)}</div><div class="sku-copy"><div class="sku-name">${escapeHtml(x.name)}</div><div class="sku-meta">${x.spec?`<span class="meta-pill spec">${escapeHtml(x.spec)}</span>`:''}<span class="meta-pill">${categoryIcons[x.category]||'📦'} ${escapeHtml(x.category)}</span><span class="meta-pill">${escapeHtml(x.supplier)}</span></div><div class="v3-stock-hint">${escapeHtml(v3Hint(x))}${use?` · 周耗≈${fmt(use)}`:''}</div></div></div><div class="stock-value v3-${v3Level(x)}">${fmt(x.qty)} <small>${escapeHtml(x.unit)}</small></div></div><div class="sku-actions v3-four"><button class="mini-btn" data-action="operate" data-id="${x.id}">到货/报损</button><button class="mini-btn" data-action="order" data-id="${x.id}">＋订货</button><button class="mini-btn" data-action="set" data-id="${x.id}">设库存</button><button class="mini-btn" data-v3-edit="${x.id}">编辑</button></div></article>`}).join(''):'<div class="empty">没有匹配的 SKU</div>';
  const alerts=v3Skus().filter(x=>['zero','red','yellow'].includes(v3Level(x))).length,pending=Object.values(state.order).filter(v=>Number(v)>0).length;document.getElementById('stockSummary').innerHTML=`<div class="summary-card"><span>📚 SKU总数</span><b>${v3Skus().length}</b></div><div class="summary-card"><span>⚠️ 需留意</span><b>${alerts}</b></div><div class="summary-card"><span>🛒 草稿</span><b>${pending}</b></div>`;
};
renderCount=function(){document.getElementById('countList').innerHTML=v3Cats().map(cat=>{const rows=v3Skus().filter(x=>x.category===cat);if(!rows.length)return'';return `<section class="count-group"><div class="count-title"><span class="category-bubble">${categoryIcons[cat]||'📦'}</span>${escapeHtml(cat)}</div>${rows.map(x=>`<div class="count-row"><div class="count-label"><span class="count-mini-icon">${v3Icon(x)}</span><div class="count-label-text"><strong>${escapeHtml(x.name)}</strong><small>${escapeHtml(x.spec||'无规格')} · 当前 ${fmt(x.qty)} ${escapeHtml(x.unit)}</small></div></div><div class="input-unit"><input class="count-input" data-id="${x.id}" type="number" step="0.1" inputmode="decimal" placeholder="—"><span>${escapeHtml(x.unit)}</span></div></div>`).join('')}</section>`}).join('')};

function v3RenderOrder(){document.querySelectorAll('[data-v3-order-mode]').forEach(b=>b.classList.toggle('active',b.dataset.v3OrderMode===v3OrderMode));document.getElementById('v3DraftPane').classList.toggle('hidden',v3OrderMode!=='draft');document.getElementById('v3PlacedPane').classList.toggle('hidden',v3OrderMode!=='placed');if(v3OrderMode==='draft')v3RenderDraft();else v3RenderPlaced()}
renderOrder=v3RenderOrder;
function v3RenderDraft(){const ids=Object.keys(state.order).filter(id=>Number(state.order[id])>0),rows=ids.map(id=>sku(id)).filter(Boolean).filter(x=>!state.hiddenSkuIds.includes(x.id)).filter(x=>activeSupplier==='全部'||x.supplier===activeSupplier);document.getElementById('orderList').innerHTML=rows.length?rows.map(x=>`<article class="sku-card order-row"><div class="order-left"><span class="count-mini-icon">${v3Icon(x)}</span><div><div class="sku-name">${escapeHtml(x.name)}</div><div class="sku-meta"><span class="meta-pill spec">${escapeHtml(x.spec||'无规格')}</span><span class="meta-pill">${escapeHtml(x.supplier)}</span>${v3Suggestion(x)>0?`<span class="meta-pill v3-suggest">建议 ${fmt(v3Suggestion(x))}</span>`:''}</div></div></div><div class="input-unit"><input class="order-input" data-id="${x.id}" value="${fmt(state.order[x.id])}" type="number" step="0.1" inputmode="decimal"><span>${escapeHtml(x.unit)}</span></div><button class="icon-btn" data-remove-order="${x.id}">✕</button></article>`).join(''):'<div class="empty">还没有订货草稿 🗿</div>'}
function v3Generate(){let n=0;v3Skus().forEach(s=>{const q=v3Suggestion(s);if(q>0&&!state.order[s.id]){state.order[s.id]=q;n++}});saveState();renderAll();showToast(n?`已加入 ${n} 个建议`:'目前没有可计算的新建议')}
function v3Place(){const entries=Object.entries(state.order).filter(([,v])=>Number(v)>0).map(([id,v])=>({s:sku(id),v:Number(v)})).filter(x=>x.s&&!state.hiddenSkuIds.includes(x.s.id)).filter(x=>activeSupplier==='全部'||x.s.supplier===activeSupplier);if(!entries.length){showToast('当前筛选下没有草稿');return}const groups=new Map();entries.forEach(x=>{if(!groups.has(x.s.supplier))groups.set(x.s.supplier,[]);groups.get(x.s.supplier).push(x)});groups.forEach((rows,supplier)=>{const o={id:crypto.randomUUID?.()||String(Date.now()+Math.random()),supplier,createdAt:stamp(),status:'placed',partial:false,items:rows.map(({s,v})=>({skuId:s.id,skuName:s.name,unit:s.unit,orderedQty:v,actualQty:v,reviewed:false}))};state.placedOrders.push(o);rows.forEach(({s})=>delete state.order[s.id]);addHistory('order',rows[0].s.id,`${supplier}：${rows.length} 个 SKU 已下单`,'',{orderId:o.id})});saveState();v3OrderMode='placed';renderAll();showToast('已转入“已下单”')}
function v3OrderItem(orderId,skuId){const o=state.placedOrders.find(x=>x.id===orderId);return{o,item:o?.items.find(i=>i.skuId===skuId)}}
function v3ReceiveRow(o,item,done){const s=sku(item.skuId),q=Number(item.actualQty)||0,cls=item.reviewed?(q===0?'v3-missing':'v3-checked'):'v3-pending';return `<div class="v3-receive-row ${cls}" data-v3-order="${o.id}" data-v3-item="${item.skuId}"><div class="v3-receive-title"><span class="count-mini-icon">${v3Icon(s)}</span><div><strong>${escapeHtml(s?.name||item.skuName)}</strong><small>订 ${fmt(item.orderedQty)} ${escapeHtml(item.unit||s?.unit||'')}</small></div></div><div class="v3-stepper"><button ${done?'disabled':''} data-v3-step="-1">−</button><input ${done?'disabled':''} class="v3-receive-qty" type="number" step="0.1" inputmode="decimal" value="${fmt(q)}"><button ${done?'disabled':''} data-v3-step="1">＋</button></div><div class="v3-receive-actions">${done?'':`<button data-v3-missing>✕ 未到</button><button data-v3-reviewed>✓ 核对</button>`}<span>${item.reviewed?(q===0?'未到':`实到 ${fmt(q)} ${escapeHtml(item.unit||s?.unit||'')}`):'待核对'}</span></div></div>`}
function v3RenderPlaced(){const orders=state.placedOrders.slice().reverse();document.getElementById('v3PlacedList').innerHTML=orders.length?orders.map(o=>{const reviewed=o.items.filter(i=>i.reviewed).length,done=o.status==='received';return `<article class="v3-placed-card ${done?'done':''}"><div class="v3-placed-head"><div><div class="eyebrow">${escapeHtml(o.supplier||'订单')}</div><h3>${new Date(o.createdAt).toLocaleString('zh-CN',{month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit'})}</h3></div><span>${done?(o.partial?'部分到货':'已收货'):`已核对 ${reviewed}/${o.items.length}`}</span></div><div class="v3-receive-list">${o.items.map(i=>v3ReceiveRow(o,i,done)).join('')}</div>${done?`<div class="v3-finished">库存已按实际到货数量入账。</div>`:`<button class="btn primary large" data-v3-finish="${o.id}" ${reviewed===o.items.length?'':'disabled'}>完成本次收货</button>`}</article>`}).join(''):'<div class="empty">还没有“已下单”订单 📦</div>'}
function v3Step(orderId,skuId,d){const {o,item}=v3OrderItem(orderId,skuId);if(!o||!item||o.status==='received')return;item.actualQty=Math.max(0,Math.round((Number(item.actualQty)+d)*10)/10);item.reviewed=false;saveState();v3RenderPlaced()}
function v3Qty(orderId,skuId,v){const {o,item}=v3OrderItem(orderId,skuId);if(!o||!item||o.status==='received')return;item.actualQty=Math.max(0,Number(v)||0);item.reviewed=false;saveState();v3RenderPlaced()}
function v3Mark(orderId,skuId,missing){const {o,item}=v3OrderItem(orderId,skuId);if(!o||!item||o.status==='received')return;if(missing)item.actualQty=0;item.reviewed=true;saveState();v3RenderPlaced();showToast(missing?'已标记未到':'已核对')}
function v3Finish(id){const o=state.placedOrders.find(x=>x.id===id);if(!o||o.status==='received')return;if(o.items.some(i=>!i.reviewed)){showToast('还有货品没核对');return}let partial=false;o.items.forEach(i=>{const s=sku(i.skuId),q=Number(i.actualQty)||0;if(q!==Number(i.orderedQty))partial=true;if(s&&q>0){s.qty=Number(s.qty)+q;addHistory('arrival',s.id,`+${fmt(q)} ${s.unit} → ${fmt(s.qty)} ${s.unit}`,`${o.supplier} 订单实到`,{orderId:o.id})}});o.status='received';o.receivedAt=stamp();o.partial=partial;saveState();renderAll();showToast(partial?'已按实际数量入库（有差异）':'收货完成')}
